name: permission_app
description: تطبيق Flutter لطلب أذونات الملفات والرسائل SMS
publish_to: 'none' # لمنع نشر الحزمة على pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true